import Head from 'next/head'
import { useRouter } from "next/router";

import MainLayout from "layout/MainLayout/MainLayout";
import Title from "components/home/Title/Title";
import HomeItemList from "components/home/HomeItemList/HomeItemList";
import {HomeItemProps} from "../components/home/HomeItem/HomeItem";

export default function Home() {
  const router = useRouter();

  const playListInfo: HomeItemProps[] = [
    {
      title: '음악 제목 01',
      url: '#001',
      imageUrl: '',
    },
    {
      title: '음악 제목 02',
      url: '#002',
      imageUrl: '',
    },
    {
      title: '음악 제목 03',
      url: '#003',
      imageUrl: '',
    },
    {
      title: '음악 제목 04',
      url: '#004',
      imageUrl: '',
    },
    {
      title: '음악 제목 05',
      url: '#005',
      imageUrl: '',
    },
  ]


  return (
    <MainLayout title={"illusion"}>
      <Head>
        <title>ILLUSION</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={"/favicon.ico"} />
      </Head>

      <Title title={'TIME X MUSIC'} direction={'left'} />

      <Title title={'PLAYLIST'} direction={'right'} />
      <HomeItemList listInfo={playListInfo} />

      <Title title={'GAME X TEST'} direction={'left'} />
      <HomeItemList listInfo={playListInfo} borderRadius={50} />

      <button
        onClick={() => {
          router.push('/game');
        }}
      >
        게임 모음
      </button>
      <button
        onClick={() => {
          router.push('/write');
        }}
      >
        텍스트 에디터
      </button>
    </MainLayout>
  )
}
