import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useRouter} from "next/router";

import MainLayout from "../layout/MainLayout/MainLayout";
import Title from "../components/home/Title/Title";

export default function Home() {
  const router = useRouter();

  return (
    <MainLayout title={"illusion"}>
      <div className={styles.container}>
        <Head>
          <title>ILLUSION</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href={"/favicon.ico"} />
        </Head>

        <Title title={'TIME X MUSIC'} direction={'left'} />
        <Title title={'PLAYLIST'} direction={'right'} />
        <Title title={'GAME X TEST'} direction={'left'} />


        <button
          onClick={() => {
            router.push('/game');
          }}
        >
          게임 모음
        </button>
        <button
          onClick={() => {
            router.push('/write');
          }}
        >
          텍스트 에디터
        </button>
      </div>
    </MainLayout>
  )
}
